apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: NodePort

  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    frontend: boot-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "frontend"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        frontend: boot-frontend
    spec:
      containers:
        - name: app-nginx
          image: #GCP/web-frontend:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
           - containerPort: 80
