apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  serviceName: redis-slave
  replicas: 4
  template:
    metadata:
      labels:
        app: redis-slave
        component: redis-cache
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-slave
        image: #GCP/redis-sentinel
        imagePullPolicy: Always
        env:
        - name: TYPE
          value: SLAVE
        - name: MASTER
          value: redis-master
        ports:
        - containerPort: 6379
          name: redis-slave

#TODO HEALTH CHECKS