kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        component: redis-cache
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-master
        image: #GCP/redis-sentinel
        imagePullPolicy: Always
        env:
        - name: TYPE
          value: MASTER
        ports:
        - containerPort: 6379
          name: redis-master
        volumeMounts:
        - mountPath: /var/redis-data
          name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-claim
