apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  ports:
  - port: 6379
    name: redis-master
  clusterIP: None
  selector:
    app: redis-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-master
        image: gcr.io/cloudjlb-eventer/redis-sentinel
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-master

