apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: boot
  annotations:
      kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: self-signed-cert
  backend:
    serviceName: frontend
    servicePort: 80