apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  type: NodePort

  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "spring-boot"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: gcr.io/cloudjlb-eventer/spring-boot-app:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 8080
