apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: gcr.io/cloudjlb-eventer/redis-sentinel
        imagePullPolicy: Always
        env:
        - name: TYPE
          value: SENTINEL
        - name: MASTER
          value: redis-master
        ports:
        - containerPort: 26379
          name: redis-sentinel