apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  ports:
  - port: 26379
    name: redis-sentinel
  clusterIP: None
  selector:
    app: redis-sentinel
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: gcr.io/cloudjlb-eventer/redis-sentinel
        imagePullPolicy: Always
        env:
        - name: TYPE
          value: SENTINEL
        - name: MASTER
          value: redis-master.default.svc.cluster.local
        ports:
        - containerPort: 26379
          name: redis-sentinel